### ISSUE TITLE
Syntax Analysis

### ISSUE THREAD

**Issue by gfantonib** [jos-felipe/minishell#15]
1. Break the input into words and operators, obeying the quoting rules described in "quoting". These tokens are separated by metacharacters. Alias expansion is performed by this step.

2. Parses the tokens into simple and compound commands.

**Comment by gfantonib** [comment]
control operator:
A token that performs a control function. It is a newline or one of the following: ‘||’, ‘&&’, ‘&’, ‘;’, ‘;;’, ‘;&’, ‘;;&’, ‘|’, ‘|&’, ‘(’, or ‘)’.

metacharacter:
A character that, when unquoted, separates words. A metacharacter is a space, tab, newline, or one of the following characters: ‘|’, ‘&’, ‘;’, ‘(’, ‘)’, ‘<’, or ‘>’.

**Comment by jos-felipe** [comment]
Tests:

- [ ]  `echo` 
- [ ] `echo -n Mephis > outfile`
- [ ] `cat -e < infile`
- [ ] `> outfile; >outfile`
- [ ]  `< infile; <infile`
- [ ] `echo -n Mephis >> outfile`
- [ ] `echo -n Mephis`
