### ISSUE TITLE
Expansion

### ISSUE THREAD

**Issue by gfantonib** [jos-felipe/minishell#7]
Handle **environment variables** (**$** followed by a sequence of characters) which should expand their values.

**Comment by jos-felipe** [comment]
List of tests

~/proj>echo var=hello
var=hello
~/proj>var=hello 
~/proj>echo word$var
wordhello
~/proj>echo word$var$
wordhello$
~/proj>var=one
~/proj>var=two
~/proj>var2=two
~/proj>var3=three
~/proj>echo one$var2$var3
onetwothree
~/proj>echo one$var2$var3$
onetwothree$
~/proj>echo one$var2midlle$var3$
onethree$
~/proj>echo $dklsfsdfk

~/proj>echo $$
30284
~/proj>echo $$LANG
30284LANG
~/proj>echo $$LANG$
30284LANG$
